services:
  postgres_db:
    image: postgres:16
    container_name: opportunity_postgres
    environment:
      POSTGRES_DB: student_opportunities_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: opportunity_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    restart: unless-stopped

  streamlit_app:
    build: .
    container_name: opportunity_streamlit
    ports:
      - "8501:8501"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: student_opportunities_db
      DB_USER: app_user
      DB_PASSWORD: app_password
    depends_on:
      - postgres_db
    restart: unless-stopped

volumes:
  postgres_data:
